USE ROLE ACCOUNTADMIN;

CREATE COMPUTE POOL IF NOT EXISTS CNO_SERVICE_FUNCTIONS
       MIN_NODES = 1
       MAX_NODES = 1
       INSTANCE_FAMILY = 'CPU_X64_XS'
       AUTO_RESUME = TRUE
       INITIALLY_SUSPENDED = FALSE
       AUTO_SUSPEND_SECS = 60;

CREATE DATABASE IF NOT EXISTS CNO_SERVICE_FUNCTIONS;

CREATE SCHEMA IF NOT EXISTS CNO_SERVICE_FUNCTIONS.DATA;

CREATE IMAGE REPOSITORY IF NOT EXISTS CNO_SERVICE_FUNCTIONS.DATA.IMAGE_REPOSITORY;

GRANT USAGE ON COMPUTE POOL CNO_SERVICE_FUNCTIONS TO ROLE NATIVE_APP_PUBLISHER;
GRANT USAGE ON DATABASE CNO_SERVICE_FUNCTIONS TO ROLE NATIVE_APP_PUBLISHER;
GRANT USAGE ON SCHEMA CNO_SERVICE_FUNCTIONS.DATA TO ROLE NATIVE_APP_PUBLISHER;
GRANT CREATE SERVICE ON SCHEMA CNO_SERVICE_FUNCTIONS.DATA TO ROLE NATIVE_APP_PUBLISHER;
GRANT CREATE FUNCTION ON SCHEMA CNO_SERVICE_FUNCTIONS.DATA TO ROLE NATIVE_APP_PUBLISHER;
GRANT READ ON IMAGE REPOSITORY CNO_SERVICE_FUNCTIONS.DATA.IMAGE_REPOSITORY TO ROLE NATIVE_APP_PUBLISHER;
GRANT WRITE ON IMAGE REPOSITORY CNO_SERVICE_FUNCTIONS.DATA.IMAGE_REPOSITORY TO ROLE NATIVE_APP_PUBLISHER;

