USE ROLE ACCOUNTADMIN;

CREATE IF NOT EXISTS COMPUTE POOL CNO_SERVICE_FUNCTIONS;

CREATE DATABASE IF NOT EXISTS CNO_SERVICE_FUNCTIONS;

CREATE SCHEMA IF NOT EXISTS CNO_SERVICE_FUNCTIONS.DATA;

CREATE IMAGE REGISTRY CNO_SERVICE_FUNCTIONS.DATA.IMAGE_REGISTRY;
