USE ROLE NATIVE_APP_PUBLISHER;

DROP SERVICE IF EXISTS CNO_SERVICE_FUNCTIONS.DATA.SERVICE_FUNCTION;

DROP FUNCTION IF EXISTS CNO_SERVICE_FUNCTIONS.DATA.DEBUG(varchar);

DROP FUNCTION IF EXISTS CNO_SERVICE_FUNCTIONS.DATA.SHELL(varchar);
