USE ROLE NATIVE_APP_PUBLISHER;

SELECT SYSTEM$GET_SERVICE_LOGS('CNO_SERVICE_FUNCTIONS.DATA.service_function', 0, 'servicefunctions');

SELECT CNO_SERVICE_FUNCTIONS.DATA.DEBUG('test');

SELECT CNO_SERVICE_FUNCTIONS.DATA.SHELL('date');
